[profile.default]
src = "src"
out = "out"
libs = ["lib"]


[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
func_vis = "public"
quote_style = "double"
number_underscore = "thousands"
